language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pycodestyle --show-source --show-pep8 main.py
  - pycodestyle --show-source --show-pep8 algorithm.py
